### ISSUE TITLE
Missing submodule repository

### ISSUE THREAD

**Issue by SamB** [KomaEc/crown#8]
Your `.gitmodules` file says:

https://github.com/KomaEc/crown/blob/7243d689be588cacc2a47ba750e2ceca2fdb8c98/.gitmodules#L1-L3

... but there is no (publicly-visible) repository at <https://github.com/KomaEc/crown-annotation>.

**Comment by amandokh** [comment]
I am facing this issue as well. @KomaEc can you please make the required submodule publicly availabe.

**Comment by KomaEc** [comment]
Hi everyone, 
Apologies for the delayed response, and thank you so much for your interest in this repository.
The **master** branch (which includes the private submodule) was an attempt to refactor the original implementation of crown in the  **artifact** branch. Due to time constraints, I'm not able to continue with the refactoring. Could I kindly ask you to switch to the **artifact** branch instead?
